---
# defaults file for esxi_scg

## Choose Setup
esxi_scg_ntp: false
esxi_scg_lockdown: false
esxi_scg_ssh: false

## General
vcenter_hostname: 'vcenter.lab.local'
vcenter_username: 'Administrator@vsphere.local'
vcenter_password: 'C0mpl3x!'
cluster_name: 'lab'

## NTP
ntp1: '192.168.2.100'
ntp2: '192.168.2.101'
ntp3: '192.168.2.102'
ntp4: '192.168.2.103'
