---
# defaults file for esxi_scg

## Choose Setup
esxi_scg_ntp: false
esxi_scg_lockdown: false
esxi_scg_ssh: false
esxi_scg_accountlockfailures: false
esxi_scg_accountunlocktime: false
esxi_scg_passwordhistory: false
esxi_scg_passwordpolicies: false
esxi_scg_dcuitimeout: false
esxi_scg_mob: false
esxi_scg_networkbpdu: false
esxi_scg_shellinteractivetimeout: false
esxi_scg_shelltimeout: false
esxi_scg_shellwarning: false
esxi_scg_tlsprotocols: false
esxi_scg_transparentpagesharing: false
esxi_scg_vibtrustedbinaries: false

## General
vcenter_hostname: 'vcenter.lab.local'
vcenter_username: 'Administrator@vsphere.local'
vcenter_password: 'C0mpl3x!'
cluster_name: 'lab'

## NTP
ntp1: '192.168.2.100'
ntp2: '192.168.2.101'
ntp3: '192.168.2.102'
ntp4: '192.168.2.103'
