---
# defaults file for esxi_scg

## Choose Setup
esxi_scg_ntp: false

## General
vcenter_hostname: 'vcenter.lab.local'
vcenter_username: 'Administrator@vsphere.local'
vcenter_password: 'C0mpl3x!'
cluster_name: 'lab'

## NTP
ntp1: '192.168.2.100'
ntp2: '192.168.2.101'
