- name: Set Transparent Page Sharing Restriction
  vmware_host_config_manager:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    cluster_name: "{{ cluster_name }}"
    validate_certs: no
    options:
      "Mem.ShareForceSalting": 2
