---
- name: Manage NTP Firewall Rules
  community.vmware.vmware_host_firewall_manager:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    cluster_name: "{{ cluster_name }}"
    validate_certs: false
    rules:
      - name: ntpClient
        enabled: true
        allowed_hosts:
          all_ip: false
          ip_address:
            - "{{ ntp1 }}"
            - "{{ ntp2 }}"
            - "{{ ntp3 }}"
            - "{{ ntp4 }}"
- name: Set NTP servers
  community.vmware.vmware_host_ntp:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    cluster_name: "{{ cluster_name }}"
    validate_certs: false
    ntp_servers:
      - "{{ ntp1 }}"
      - "{{ ntp2 }}"
      - "{{ ntp3 }}"
      - "{{ ntp4 }}"
- name: Set NTP Service
  community.vmware.vmware_host_service_manager:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    cluster_name: "{{ cluster_name }}"
    validate_certs: false
    service_name: ntpd
    state: start
    service_policy: false
