- name: Set Disabled Protocols
  vmware_host_config_manager:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    cluster_name: "{{ cluster_name }}"
    validate_certs: no
    options:
      "UserVars.ESXiVPsDisabledProtocols": "sslv3,tlsv1,tlsv1.1"