- name: Set VIB Trusted Binaries Restriction
  vmware_host_config_manager:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    cluster_name: "{{ cluster_name }}"
    validate_certs: false
    options:
      "VMkernel.Boot.execInstalledOnly": true
